In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
## Define the vocabulary size
voc_size=10000


In [ ]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr


[[8017, 5074, 4900, 2628],
 [8017, 5074, 4900, 9858],
 [8017, 6999, 4900, 3554],
 [8329, 2152, 713, 3446, 5508],
 [8329, 2152, 713, 3446, 4945],
 [2540, 8017, 546, 4900, 8370],
 [7700, 3303, 4578, 3446]]

In [ ]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences  
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8017 5074 4900 2628]
 [   0    0    0    0 8017 5074 4900 9858]
 [   0    0    0    0 8017 6999 4900 3554]
 [   0    0    0 8329 2152  713 3446 5508]
 [   0    0    0 8329 2152  713 3446 4945]
 [   0    0    0 2540 8017  546 4900 8370]
 [   0    0    0    0 7700 3303 4578 3446]]


In [ ]:
dim=11

In [ ]:

# Create a Sequential model
model = Sequential()

model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')


In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 11)             110000    
                                                                 
Total params: 110000 (429.69 KB)
Trainable params: 110000 (429.69 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 259ms/step


array([[[-0.01639842,  0.00934479,  0.00453038,  0.04764483,
          0.01264066, -0.00127489, -0.04397267,  0.01149098,
         -0.02234172,  0.01894848,  0.0120212 ],
        [-0.01639842,  0.00934479,  0.00453038,  0.04764483,
          0.01264066, -0.00127489, -0.04397267,  0.01149098,
         -0.02234172,  0.01894848,  0.0120212 ],
        [-0.01639842,  0.00934479,  0.00453038,  0.04764483,
          0.01264066, -0.00127489, -0.04397267,  0.01149098,
         -0.02234172,  0.01894848,  0.0120212 ],
        [-0.01639842,  0.00934479,  0.00453038,  0.04764483,
          0.01264066, -0.00127489, -0.04397267,  0.01149098,
         -0.02234172,  0.01894848,  0.0120212 ],
        [ 0.0318701 , -0.00532025, -0.00605241, -0.0339821 ,
         -0.00912648, -0.04877807, -0.04505664, -0.01691036,
         -0.00612581,  0.03406263, -0.00399526],
        [-0.01703254,  0.04785147,  0.02648509, -0.00462043,
          0.02795117,  0.03423065, -0.03556865, -0.00616516,
          0.03057313, -

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 8017, 5074, 4900, 2628])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 69ms/step


array([[-0.01639842,  0.00934479,  0.00453038,  0.04764483,  0.01264066,
        -0.00127489, -0.04397267,  0.01149098, -0.02234172,  0.01894848,
         0.0120212 ],
       [-0.01639842,  0.00934479,  0.00453038,  0.04764483,  0.01264066,
        -0.00127489, -0.04397267,  0.01149098, -0.02234172,  0.01894848,
         0.0120212 ],
       [-0.01639842,  0.00934479,  0.00453038,  0.04764483,  0.01264066,
        -0.00127489, -0.04397267,  0.01149098, -0.02234172,  0.01894848,
         0.0120212 ],
       [-0.01639842,  0.00934479,  0.00453038,  0.04764483,  0.01264066,
        -0.00127489, -0.04397267,  0.01149098, -0.02234172,  0.01894848,
         0.0120212 ],
       [ 0.0318701 , -0.00532025, -0.00605241, -0.0339821 , -0.00912648,
        -0.04877807, -0.04505664, -0.01691036, -0.00612581,  0.03406263,
        -0.00399526],
       [-0.01703254,  0.04785147,  0.02648509, -0.00462043,  0.02795117,
         0.03423065, -0.03556865, -0.00616516,  0.03057313, -0.0242242 ,
        -0.033